# DO NOT EDIT THIS FILE
# This file is autogenerated by build_texture.py.

# Texture info.
TEXTURE_INFO = {
    # <id>: <swatch-size>, <num-swatches>
    "g01": [30, 3],
    "h02": [40, 35],
    "l01": [50, 21],
    "m01": [45, 21],
    "r01": [200, 1],
    "r02": [200, 1],
    "s01": [20, 3],
    "t01": [20, 12],
}

TEXTURES = {
    "g": ["g01"],
    "h": ["h02"],
    "l": ["l01"],
    "m": ["m01"],
    "r": ["r01", "r02"],
    "s": ["s01"],
    "t": ["t01"],
}
