# Woven Academy monster card data

monster_card_revision = 1

monster_card_data = [

    ["FRANKIE", {
        'element': 'air',
        'pattern': [   "@ . @",
                       ". X .",
                       ". X .",
                       ". @ .",   ],
        'image': 'birdman',
        'attack': '**',
        'actions': ['**', '*', '', ''],
        } ],
    ["PERCY", {
    	'element': 'air',
        'pattern': [   ". @ .",
                       ". . .",
                       ". @ .",
                       ". @ .",
                       "X . X",   ],
        'image': 'peryton',
        'attack': '*',
        'actions': ['*', '', '*', ''],
        } ],
    ["GRIFFITHE", {
    	'element': 'air',
        'pattern': [   "X . . .",
                       ". @ . @",
                       ". . . .",
                       ". @ . X",   ],
        'image': 'griffin',
        'attack': '*',
        'actions': ['**', '', '', '*'],
        } ],
    ["OCTAVIUS", {
    	'element': 'air',
        'pattern': [   "X . . @",
                       ". X . .",
                       ". . @ .",
                       "@ . . .",   ],
        'image': 'pigeon',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["WAYNE & BRUCE", {
    	'element': 'air',
        'pattern': [   "@ . . X",
                       ". . @ .",
                       ". @ . .",
                       ". . . X",   ],
        'image': 'bats',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["BABYFACE", {
    	'element': 'air',
        'pattern': [   ". . @ .",
                       ". X . @",
                       ". . . .",
                       "@ . X .",   ],
        'image': 'basilisk',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],


    ["BORIS", {
    	'element': 'fire',
        'pattern': [   "@ . @",
                       ". @ .",
                       ". . .",
                       "X . X",   ],
        'image': 'boar',
        'attack': '**',
        'actions': ['', '**', '*', ''],
        } ],
    ["BOCK", {
    	'element': 'fire',
        'pattern': [   "@ . X",
                       ". @ .",
                       "X . @",   ],
        'image': 'rooster',
        'attack': '*',
        'actions': ['', '*', '', '*'],
        } ],
    ["RAYNARD", {
    	'element': 'fire',
        'pattern': [   ". . X .",
                       ". . @ .",
                       "X @ . .",
                       ". . . @",   ],
        'image': 'fox',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["HAZEL", {
    	'element': 'fire',
        'pattern': [   ". . @ .",
                       ". . X .",
                       "X @ . .",
                       ". . . @",   ],
        'image': 'hare2',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["POX", {
    	'element': 'fire',
        'pattern': [   ". . @",
                       "@ @ .",
                       ". . .",
                       ". X .",
                       ". . X",   ],
        'image': 'pantera',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["WILLIAM", {
    	'element': 'fire',
        'pattern': [   "X . . .",
                       ". . @ X",
                       "@ . . .",
                       ". . . @",   ],
        'image': 'goat',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],


    ["BAMBAM & FIFI", {
    	'element': 'earth',
        'pattern': [   "@ @ .",
                       "@ . .",
                       ". . X",
                       ". X .",   ],
        'image': 'mandragora',
        'attack': '*',
        'actions': ['', '', '*', ''],
        } ],
    ["BENJAMIN", {
    	'element': 'earth',
        'pattern': [   ". . . X",
                       ". @ . @",
                       "@ . . .",
                       ". . . X",   ],
        'image': 'draconcopedes',
        'attack': '*',
        'actions': ['*', '', '', '*'],
        } ],
    ["DRUMMER", {
    	'element': 'earth',
        'pattern': [   "@ @ @",
                       ". . .",
                       ". . .",
                       ". X .",
                       ". X .",   ],
        'image': 'catoblepas',
        'attack': '***',
        'actions': ['', '*', '', ''],
        } ],
    ["PETER", {
    	'element': 'earth',
        'pattern': [   "X . . .",
                       ". @ . @",
                       ". . X .",
                       "@ . . .",   ],
        'image': 'hare3b',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["DOGBOY & LEO", {
    	'element': 'earth',
        'pattern': [   ". @ . .",
                       "@ @ . .",
                       ". . . X",
                       ". . X .",   ],
        'image': 'cephos',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["JACK", {
    	'element': 'earth',
        'pattern': [   ". . @ .",
                       ". X . @",
                       ". . . .",
                       "X . . @",   ],
        'image': 'hare',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],


    ["COTTONTAIL", {
    	'element': 'water',
        'pattern': [   ". . @ X",
                       ". . @ .",
                       ". . . .",
                       "X . . @",   ],
        'image': 'hare3',
        'attack': '*',
        'actions': ['*', '*', '*', ''],
        } ],
    ["JON-JOHN", {
    	'element': 'water',
        'pattern': [   ". . . @",
                       ". . X .",
                       ". X . .",
                       "@ . . @",   ],
        'image': 'giant',
        'attack': '***',
        'actions': ['', '', '*', '*'],
        } ],
    ["RAZZLE DASH", {
    	'element': 'water',
        'pattern': [   "@ . . .",
                       ". . @ .",
                       ". @ X .",
                       ". . . X",   ],
        'image': 'unicorn',
        'attack': '*',
        'actions': ['', '', '', '**'],
        } ],
    ["CROCO", {
    	'element': 'water',
        'pattern': [   ". . @",
                       "@ . .",
                       ". @ .",
                       ". . .",
                       "X . X",   ],
        'image': 'cocodrillus',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["MADGE", {
    	'element': 'water',
        'pattern': [   ". . X .",
                       ". . @ X",
                       "@ . . .",
                       ". . . @",   ],
        'image': 'cerastes',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],
    ["WINSTON", {
    	'element': 'water',
        'pattern': [   ". . @ .",
                       ". . X .",
                       "@ X . .",
                       ". . . @",   ],
        'image': 'bear',
        'attack': '*',
        'actions': ['*', '', '*', '*'],
        } ],

    
]
