# DO NOT EDIT THIS FILE
# This file is autogenerated by build_texture.py.

# Texture info.
TEXTURE_INFO = {
    # <id>: <swatch-size>, <num-swatches>
    "l01": [50, 21],
    "m01": [45, 21],
    "h02": [40, 35],
}

TEXTURES = {
    "l": ["l01"],
    "m": ["m01"],
    "h": ["h02"],
}
